### ISSUE TITLE
propose logo

### ISSUE THREAD

**Issue by dee-y** [kping0/SimpleSecureChat#26]
Hello @kping0  i am a graphic designer. I would like to know if you would be interested in me making a logo for this project. If you would have me, i would make a logo for you, and it's free.

**Comment by kping0** [comment]
Sure. If you do it would be very appreciated!

**Comment by dee-y** [comment]
Hi @kping0, i have made a simple design below for the project, very minimal. What do you think?

**Comment by kping0** [comment]
Much appreciated! Will incorporate very shortly.

**Comment by kping0** [comment]
closing the issue now, if you have any other changes to suggest, open up another issue please.
